//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Life_Planner {
    
    
    public partial class Test {
        
        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button1;
        
        /// <summary>
<<<<<<< HEAD
        /// S1 control.
=======
        /// Table1 control.
>>>>>>> f6e423c137678bfc045b63a33542ac7b34eee90a
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.TextBox S1;
=======
        protected global::System.Web.UI.WebControls.Table Table1;
>>>>>>> f6e423c137678bfc045b63a33542ac7b34eee90a
    }
}
